services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    restart: always

volumes:
  prisma:
  uploads:
